### PR TITLE
Support scikit-learn v0.20

### LINKED ISSUE #13: AttributeError: 'SphericalKMeans' object has no attribute '_check_fit_data'
I've been getting a 
`AttributeError: 'SphericalKMeans' object has no attribute '_check_fit_data'`

error every time I try to run a SphericalKMeans fit. Diving a little further, it looks like the **_check_fit_data** method only exists in two locations in the repository...

Line 318 in spherical_kmeans.py (the line that throws the error in this case).

Line 772 in von_mises_fisher_mixture.py where it seems to be a defined method.

Based on what I can see from the imports, it looks like the **_check_fit_data** doesn't actually exist in the context of spherical_kmeans.py, so the error kind of makes sense.

Could this be the result of some accidental deletions? I went through the commit history and couldn't find anything that immediately seemed like the issue. Or is there something very obvious that I'm missing... wouldn't be the first time :)

Also as an FYI, I'm running Python 3.6.4.

### PR DESCRIPTION
**Pull request by cv3d**
resolves #13

### CODE REVIEW

File: requirements.txt [hunk 1]
```diff
@@ -1,6 +1,6 @@
 numpy
 scipy
-scikit-learn>=0.19.0
+scikit-learn>=0.19.1
```
Comment (jasonlaska) [inline requirements.txt]: Have you validated that this also works with sklearn 0.20 as well?

File: spherecluster/spherical_kmeans.py [hunk 2]
```diff
@@ -303,7 +320,7 @@ def __init__(
         self.n_jobs = n_jobs
         self.normalize = normalize
 
-    def fit(self, X, y=None):
+    def fit(self, X, y=None, sample_weight=None):
         """Compute k-means clustering.
```
Comment (jasonlaska) [inline spherecluster/spherical_kmeans.py]: The doc-string should probably be updated here to mention sample_weight.

**Comment by jasonlaska** [comment]
@cv3d  This has been merged, please feel free to delete your branch
